### ISSUE TITLE
Setting config values to bad types doesn't fail validation

### ISSUE THREAD

**Issue by mmdriley** [pulumi/pulumi-terraform#114]
While working on https://github.com/pulumi/pulumi-terraform/issues/48

This `Pulumi.yaml` should cause a validation failure:
```yaml
name: example
runtime: nodejs
stacks:
  example:
    config:
      aws:config:assumeRole: abc
```

because `assumeRole` is supposed to be a list of objects. But the provider initializes without complaint.
